### ISSUE TITLE
config for solving for e

### ISSUE THREAD

**Issue by 10kmotorola** [RealRTTV/chatcalc#14]
whenever just typing `e` into chat, it tries to solve. it would be nice to have an option in the config to turn this off, or maybe make it only look for `(e)` or something by default? i request since it's kinda unecessary with how little e is used in equations vs. in normal chatting. thanks :)

**Comment by RealRTTV** [comment]
this originally was a feature, can you give me a circumstance when this would cause problems?

**Comment by 10kmotorola** [comment]
it doesn't cause any serious problems, but one thing that's happened before is when using tab to auto complete something that starts with e it'll solve instead

**Comment by RealRTTV** [comment]
yeah, i changed that so tabbing stuff autocompletes before evaluates (like commands), that way the `e` issue isn't encountered

**Comment by 10kmotorola** [comment]
oh nice, it's still just distracting to me how the e solving will cover up the autocomplete list. if you don't think its an issue, then no worries if you'd like to close this ^^
