### ISSUE TITLE
Pressing tab after a space inserts `NaN` instead of opening or accepting suggestions

### ISSUE THREAD

**Issue by hibiii** [RealRTTV/chatcalc#2]
**Steps to reproduce:**
- Open chat and press tab
- Or, if there is text already input, add a space before tabbing.

**Expected behavior:**
If there isn't an expression, then normal tab behavior: search usernames if not a chat message, accept command suggestions, etc.

**Observed behavior:**
`NaN` is placed in the chat input box instead. This is most apparent when using a command, where muscle memory might make you accidentally insert `/setblock NaN NaN NaN chest`.

Note: I presume it's seeing an empty expression, thus taking precedence over vanilla mechanics, and evaluating it. This does not happen if there's a non-empty non-expression.

**Comment by RealRTTV** [comment]
im so sorry, i somehow never saw this, fixing it asap

**Comment by RealRTTV** [comment]
ok, seems that I fixed it a while ago, I'm so so so so so so sorry I never saw this. ♥ ♥ ♥

**Comment by RealRTTV** [comment]
https://github.com/RealRTTV/chatcalc/commit/023fc0c3a820bacdee13a26266723dce212e6dc3
