### ISSUE TITLE
output format

### ISSUE THREAD

**Issue by teodortomas** [RealRTTV/chatcalc#3]
Hello, is it possible to set the output format to for example: 3400 instead of 3 400 ? thanks.

**Comment by RealRTTV** [comment]
I'm presuming the space is there from the `decimal_format` you can remove the delimiter (the space) by using the help dialog for decimal format `decimal_format? -> TAB` I'm presuming your pc's language uses spaces for delimeters so changing it to something like `decimal_format=#.## -> TAB` should fix it

**Comment by teodortomas** [comment]
> I'm presuming the space is there from the `decimal_format` you can remove the delimiter (the space) by using the help dialog for decimal format `decimal_format? -> TAB` I'm presuming your pc's language uses spaces for delimeters so changing it to something like `decimal_format=#.## -> TAB` should fix it

Where can i change this please?

**Comment by RealRTTV** [comment]
you type it in chat

**Comment by teodortomas** [comment]
I just found out that I was using version 3.0.11 which is strange. It didn't have those decimal_format? commands, so I downloaded the latest version 3.0.6 from here, and now the mod does nothing, no calculations, no commands. What should I do?
